# Site settings
site: Roro's Blog
title: Lost in the sauce
keywords: ephesus, blog
description: >-
  Ephesus - Minimalist Jekyll Theme
lang: en-US
timezone:  Europe/Amsterdam
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Rocheandley Kwidama
  bio: Platform Engineer / Cybersecurity Student @hanze <br> Co-Founder @kenepatech <br> Open Source /#linux
  picture: assets/images/profile.jpg 
  github: rorobig # github username
  twitter: Walking_dolphin # twitter username
  facebook: onepase # facebook username
  instagram: skittlesmclovingit # instagram username
  youtube: https://www.youtube.com/channel/UCqt-IWYAHBzrfe7EakDZNqQ # youtube username
  linkedin: rocheandley-kwidama # linkedin username
  email: rkwidama@hotmail.com # email adress


# URL settings
url:  # Domain Name of host. [username].github.io for github pages
fullurl: "https://rorobig.github.io"
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false